#!/bin/bash

oldcd=$(pwd)
package=$(find src -mindepth 1 -maxdepth 1 -not -name '*.egg-info' | head -n1)

cp .coveragerc "$package"
cd "$package"
coverage run -m unittest discover -s ../../tests -t ../.. -v
mv .coverage "$oldcd"
cd "$oldcd"
coverage html
rm "$package"/.coveragerc

find "$package" -type f -name '*.py' -exec pycolor pylint {} \+

find "$package" -type f -name '*.py' -exec mypy {} \+
find tests -type f -name '*.py' -exec mypy --ignore-missing-imports {} \+
